### ISSUE TITLE
Assalomu aleykum, hero section dagi rasmni img qilib ketibsiz, background-img qisez yaxshiroq bo'lardi.

### ISSUE THREAD

**Issue by JumabaevZiyodilla** [SayramovAzizbek/Azizbek-Easybank#1]

**Comment by SayramovAzizbek** [comment]
Voaleykum Assalom, Assalomu Aleykum!
Hero sectiondagi rasm bu orga fondagi section ga bg-img qilib berilgan telefon rasm esa img qilib berilgan u bu yerda ma'no anglatyabdi, va bu application haqida shuning uchun img qilib qo'yilgan
