### ISSUE TITLE
Assalomu aleykum, hero section dagi img iz tepaga ketib qolibdi figmada sal pastroq ko'rsatilgan.

### ISSUE THREAD

**Issue by JumabaevZiyodilla** [SayramovAzizbek/Azizbek-Easybank#2]
![Screenshot_1](https://user-images.githubusercontent.com/107662716/177065215-140fc815-7944-4aba-b52d-a92471c5769d.png)

**Comment by SayramovAzizbek** [comment]
Voaleykum Assalom, Assalomu Aleykum!
TO'g'risi rasmingiz yaxshi ko'rinmayapti, va o'ylaymanki  rasm to'g'ri tushgan chunki rasmdagu accaunt yozuvini tepasida ozgina joy bor, va menda ham huddi shunaqa joy bor, balkim u sizning qurilmangizdandir
